from openers import *

simpletext = {
    '.0': open_txt,
    '.1st': open_txt,
    '.600': open_txt,
    '.602': open_txt,
    '.abw': open_txt,
    '.acl': open_txt,
    '.afp': open_txt,
    '.ami': open_txt,
    '.amigaguide': open_txt,
    '.ans': open_txt,
    '.asc': open_txt,
    '.aww': open_txt,
    '.ccf': open_txt,
    '.cwk': open_txt,
    '.dbk': open_txt,
    '.doc': open_txt,
    '.docm': open_txt,
    '.dot': open_txt,
    '.dotx': open_txt,
    '.egt': open_txt,
    '.epub': open_txt,
    '.ezw': open_txt,
    '.fdx': open_txt,
    '.ftm': open_txt,
    '.ftx': open_txt,
    '.gdoc': open_txt,
    '.hwp': open_txt,
    '.hwpml': open_txt,
    '.log': open_txt,
    '.lwp': open_txt,
    '.mbp': open_txt,
    '.md': open_txt,
    '.me': open_txt,
    '.mcw': open_txt,
    '.nb': open_txt,
    '.nbp': open_txt,
    '.neis': open_txt,
    '.odm': open_txt,
    '.ott': open_txt,
    '.omm': open_txt,
    '.pages': open_txt,
    '.pap': open_txt,
    '.pdax': open_txt,
    '.quox': open_txt,
    '.rtf': open_txt,
    '.rpt': open_txt,
    '.sdw': open_txt,
    '.se': open_txt,
    '.stw': open_txt,
    '.sxw': open_txt,
    '.tex': open_txt,
    '.info': open_txt,
    '.troff': open_txt,
    '.txt': open_txt,
    '.uof': open_txt,
    '.uoml': open_txt,
    '.via': open_txt,
    '.wpd': open_txt,
    '.wps': open_txt,
    '.wpt': open_txt,
    '.wrd': open_txt,
    '.wrf': open_txt,
    '.wri': open_txt,
    '.xps': open_txt,
    '.ahk' : open_txt,
    '.applescript' : open_txt,
    '.as' : open_txt,
    '.au3' : open_txt,
    '.bat' : open_txt,
    '.bas' : open_txt,
    '.cljs' : open_txt,
    '.cmd' : open_txt,
    '.coffee' : open_txt,
    '.duino' : open_txt,
    '.egg' : open_txt,
    '.erb' : open_txt,
    '.hta' : open_txt,
    '.ibi' : open_txt,
    '.ici' : open_txt,
    '.ijs' : open_txt,
    '..ipynb' : open_txt,
    '.itcl' : open_txt,
    '.js' : open_txt,
    '.jsfl' : open_txt,
    '.lua' : open_txt,
    '.m' : open_txt,
    '.mrc' : open_txt,
    '.ncf' : open_txt,
    '.nuc' : open_txt,
    '.nud' : open_txt,
    '.nut' : open_txt,
    '.php' : open_txt,
    '.pl' : open_txt,
    '.pm' : open_txt,
    '.ps1' : open_txt,
    '.ps1xml' : open_txt,
    '.psc1' : open_txt,
    '.psd1' : open_txt,
    '.psm1' : open_txt,
    '.py' : open_txt,
    '.pyc' : open_txt,
    '.pyo' : open_txt,
    '.r' : open_txt,
    '.rb' : open_txt,
    '.rdp' : open_txt,
    '.scpt' : open_txt,
    '.scptd' : open_txt,
    '.sdl' : open_txt,
    '.sh' : open_txt,
    '.syjs' : open_txt,
    '.sypy' : open_txt,
    '.tcl' : open_txt,
    '.vbs' : open_txt,
    '.xpl' : open_txt,
    '.ebuild' : open_txt,
}

openDict = {
    '.csv': open_csv,
    '.tsv': open_csv,
    '.xml': open_xml,
    '.disco': open_xml,
    '.lnk': open_lnk,
    '.json': open_json,
    '.excel': open_excel,
    '.pdf': open_pdf,
    '.epub': open_epub,
    '.kdbx': open_kdbx,
    '.odt': open_odt,
    '.html': open_html,
    '.xhtml': open_html,
    '.wav': open_wav,
    '.au': open_au,
    '.aiff': open_aiff,
    '.aifc': open_aifc,
    '.gzip': open_gzip,
    '.zip': open_zip,
    '.tar': open_tar,
    '.p': open_p,
    '.netrx': open_netrx,
    '.plist': open_plist,
    '.ini': open_ini,
    '.sav': open_sav
}

openDict.update(simpletext)